mutation newRuleOwnership(
  $ownerId: Int!
  $ruleId: bigint!
  $ruleMetadataId: bigint!
  $created: bigint!
) {
  insert_rule_owner(
    objects: {
      owner_id: $ownerId
      rule_id: $ruleId
      rule_metadata_id: $ruleMetadataId
      created: $created
      removed: null
      owner_mapping_source_id: 4
    }
    on_conflict: {
      constraint: pk_rule_owner
      update_columns: [removed, rule_metadata_id]
    }
  ) {
    returning {
      insertedIdLong: rule_metadata_id
    }
  }
}